/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chinesewordtrainer;

import java.awt.Font;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Deus
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
	initComponents();

	txtConsole.setEditable(false);
	txtConsole.setFont(new Font("Arial Unicode MS", txtConsole.getFont().getStyle(), 11));
	txtConsole.setDefaultLocale(java.util.Locale.SIMPLIFIED_CHINESE);
	console = new ConsoleHandler(txtConsole);
	csvReader = CSVReader.getInstance(console);
	allWords = csvReader.readWords();
	
	if(allWords == null || allWords.isEmpty()) {
	    console.logErr("ERROR: Could not build word list, allWords was null or empty. Please restart program!");
	    cboLearningMode.setEnabled(false);
	    cmdCorrect.setEnabled(false);
	    cmdLearningModeApply.setEnabled(false);
	    cmdResetWordStats.setEnabled(false);
	    cmdRevealAnswer.setEnabled(false);
	    cmdWrong.setEnabled(false);
	    
	}

	cmdRevealAnswer.setEnabled(false);
	cmdWrong.setEnabled(false);
	cmdCorrect.setEnabled(false);
	
	weightedShuffle = new WeightedShuffle(console, isDevMode);

	if (!isDevMode) {
	    cmdResetWordStats.setEnabled(false);
	    cmdResetWordStats.setVisible(false);
	}
	
	// Custom JSpinner-implementation for WeightedShuffleBeta-Spinner
	SpinnerNumberModel betaModel = new SpinnerNumberModel(1.0, 0.0, 15.0, 0.1);
	numShuffleBeta.setModel(betaModel);
	numShuffleBeta.setEditor(new javax.swing.JSpinner.NumberEditor(numShuffleBeta, "0.0"));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsole = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtQuestion = new CenteredTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtHint = new CenteredTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAnswer = new CenteredTextArea();
        cmdWrong = new javax.swing.JButton();
        cmdCorrect = new javax.swing.JButton();
        cmdEnd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cboLearningMode = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        chkL1 = new javax.swing.JCheckBox();
        chkL2 = new javax.swing.JCheckBox();
        chkL3 = new javax.swing.JCheckBox();
        chkL4 = new javax.swing.JCheckBox();
        chkL5 = new javax.swing.JCheckBox();
        chkL6 = new javax.swing.JCheckBox();
        chkL7 = new javax.swing.JCheckBox();
        chkL8 = new javax.swing.JCheckBox();
        chkL9 = new javax.swing.JCheckBox();
        chkL10 = new javax.swing.JCheckBox();
        chkL11 = new javax.swing.JCheckBox();
        chkL12 = new javax.swing.JCheckBox();
        cmdLearningModeApply = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        chkTradHanziOnlyIfDifference = new javax.swing.JCheckBox();
        numShuffleBeta = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        cmdRevealAnswer = new javax.swing.JButton();
        cmdResetWordStats = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(txtConsole);

        txtQuestion.setEditable(false);
        txtQuestion.setColumns(1);
        txtQuestion.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        txtQuestion.setRows(2);
        txtQuestion.setText("Question");
        jScrollPane2.setViewportView(txtQuestion);

        txtHint.setEditable(false);
        txtHint.setColumns(1);
        txtHint.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtHint.setRows(2);
        txtHint.setText("Click to reveal hint");
        txtHint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtHintMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(txtHint);

        txtAnswer.setEditable(false);
        txtAnswer.setColumns(1);
        txtAnswer.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        txtAnswer.setRows(2);
        txtAnswer.setText("Solution");
        jScrollPane4.setViewportView(txtAnswer);

        cmdWrong.setText("Wrong");
        cmdWrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdWrongActionPerformed(evt);
            }
        });

        cmdCorrect.setText("Correct");
        cmdCorrect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCorrectActionPerformed(evt);
            }
        });

        cmdEnd.setText("End Program");
        cmdEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEndActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Learning Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        cboLearningMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Learn simplified Hanzi", "Learn traditional Hanzi", "Learn Pinyin", "Learn Translations de -> zh", "Learn Translations zh -> de" }));
        cboLearningMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLearningModeActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Include Lessons"));

        chkL1.setText("Lesson 1");

        chkL2.setText("Lesson 2");

        chkL3.setText("Lesson 3");

        chkL4.setText("Lesson 4");

        chkL5.setText("Lesson 5");

        chkL6.setText("Lesson 6");

        chkL7.setText("Lesson 7");

        chkL8.setText("Lesson 8");
        chkL8.setToolTipText("");

        chkL9.setText("Lesson 9");

        chkL10.setText("Lesson 10");

        chkL11.setText("Lesson 11");
        chkL11.setToolTipText("");

        chkL12.setText("Lesson 12");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkL5)
                    .addComponent(chkL6)
                    .addComponent(chkL7)
                    .addComponent(chkL8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkL4)
                            .addComponent(chkL3)
                            .addComponent(chkL2)
                            .addComponent(chkL1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkL12)
                            .addComponent(chkL9)
                            .addComponent(chkL10)
                            .addComponent(chkL11))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkL1)
                    .addComponent(chkL9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkL2)
                    .addComponent(chkL10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkL3)
                    .addComponent(chkL11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkL4)
                    .addComponent(chkL12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkL5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkL6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkL7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkL8)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        cmdLearningModeApply.setText("Apply and restart session");
        cmdLearningModeApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLearningModeApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboLearningMode, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmdLearningModeApply, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cboLearningMode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdLearningModeApply, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        chkTradHanziOnlyIfDifference.setText("Traditional Hanzi: Show only words where trad. Hanzi differs from simplified");

        numShuffleBeta.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 15.0d, 1.0d));

        jLabel1.setText("Weighted shuffle Beta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numShuffleBeta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkTradHanziOnlyIfDifference))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numShuffleBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkTradHanziOnlyIfDifference)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cmdRevealAnswer.setText("Reveal Answer");
        cmdRevealAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRevealAnswerActionPerformed(evt);
            }
        });

        cmdResetWordStats.setText("Reset word stats");
        cmdResetWordStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetWordStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(cmdRevealAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdResetWordStats, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdRevealAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmdCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmdWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 253, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdResetWordStats, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboLearningModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLearningModeActionPerformed

    }//GEN-LAST:event_cboLearningModeActionPerformed

    private void cmdLearningModeApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLearningModeApplyActionPerformed
	applyLearningMode();
    }//GEN-LAST:event_cmdLearningModeApplyActionPerformed

    private void applyLearningMode() {
	String selectedMode = cboLearningMode.getSelectedItem().toString();
	System.out.println("SELECTED MODE: " + selectedMode);

	switch (selectedMode) {
	    case "Learn simplified Hanzi":
		curLearningMode = LearningMode.SIMPLIFIED_HANZI;
		txtQuestion.setFont(mediumFont);
		txtHint.setFont(smallFont);
		txtAnswer.setFont(largeFont);
		break;
	    case "Learn traditional Hanzi":
		curLearningMode = LearningMode.TRADITIONAL_HANZI;
		txtQuestion.setFont(largeFont);
		txtHint.setFont(smallFont);
		txtAnswer.setFont(largeFont);
		break;
	    case "Learn Pinyin":
		curLearningMode = LearningMode.PINYIN;
		txtQuestion.setFont(largeFont);
		txtHint.setFont(smallFont);
		txtAnswer.setFont(mediumFont);
		break;
	    case "Learn Translations de -> zh":
		curLearningMode = LearningMode.TRANSLATE_DE_ZH;
		txtQuestion.setFont(smallFont);
		txtHint.setFont(mediumFont);
		txtAnswer.setFont(largeFont);
		break;
	    case "Learn Translations zh -> de":
		curLearningMode = LearningMode.TRANSLATE_ZH_DE;
		txtQuestion.setFont(largeFont);
		txtHint.setFont(mediumFont);
		txtAnswer.setFont(smallFont);
		break;
	    default:
		curLearningMode = null;
		console.logErr("ERROR in frmMain.cboLearningModeActionPerformed(): Unknown mode \"" + selectedMode + "\". Can't switch learning mode. Please restart the program.");
	}

	lessons = new boolean[]{false, chkL1.isSelected(), chkL2.isSelected(), chkL3.isSelected(), chkL4.isSelected(), chkL5.isSelected(), chkL6.isSelected(), chkL7.isSelected(), chkL8.isSelected(),
	    chkL9.isSelected(), chkL10.isSelected(), chkL11.isSelected(), chkL12.isSelected()};

	System.out.print("Active lessons: ");

	for (int i = 1; i < lessons.length; i++) {
	    if (lessons[i]) {
		System.out.print(i + " ");
	    }
	}

	System.out.println();

	System.out.println("Building session list of words, please wait...");

	curList = new ArrayList<>();

	for (Word w : allWords) {
	    for (int i = 1; i < lessons.length; i++) {
		if (lessons[i] && Integer.parseInt(w.getLesson()) == i) {
		    if (curLearningMode == LearningMode.TRADITIONAL_HANZI && chkTradHanziOnlyIfDifference.isSelected()) {
			if (!(w.getSimpleHanzi().equals(w.getTraditionalHanzi()))) {
			    curList.add(w);
			}
		    } else {
			curList.add(w);
		    }
		}
	    }
	}

	// Collections.shuffle(curList);
	double beta = ((Number) numShuffleBeta.getValue()).doubleValue();
	weightedShuffle.interleavingShuffle(curList, beta, curLearningMode);

	if (curList.size() == 0) {
	    console.logErr("ERROR: Building session list resulted in a list with 0 entries! Aborting applyLearningMode(). Please restart program!");
	    return;
	}

	System.out.println("Successfully build session list of " + curList.size() + " words!");

	curListIndex = 0;
	cmdRevealAnswer.setEnabled(true);
	loadNextWord();
    }

    public void loadNextWord() {
	if (curListIndex == curList.size()) {
	    console.logMsg("End of list reached, restarting list...");
	    curListIndex = 0;
	}
	
	if((curSessionCorrect + curSessionWrong) % 10 == 0) {
	    console.logMsg("Saving current word data...");
	    csvReader.writeToFile(allWords);
	    console.logMsg("Current word data successfully saved!");
	}
	
	console.cprintln("  Word " + curListIndex + " / " + curList.size());

	curWord = curList.get(curListIndex);

	cmdWrong.setEnabled(false);
	cmdCorrect.setEnabled(false);

	switch (curLearningMode) {
	    case SIMPLIFIED_HANZI:
		txtQuestion.setText(curWord.getPinyin());
		txtHint.setText("Click to reveal hint");
		txtAnswer.setText("");
		break;
	    case TRADITIONAL_HANZI:
		txtQuestion.setText(curWord.getTraditionalHanzi());
		txtHint.setText("Click to reveal hint");
		txtAnswer.setText("");
		break;
	    case PINYIN:
		txtQuestion.setText(curWord.getSimpleHanzi());
		txtHint.setText("Click to reveal hint");
		txtAnswer.setText("");
		break;
	    case TRANSLATE_DE_ZH:
		txtQuestion.setText(curWord.getTranslation());
		txtHint.setText("Click to reveal hint");
		txtAnswer.setText("");
		break;
	    case TRANSLATE_ZH_DE:
		txtQuestion.setText(curWord.getSimpleHanzi());
		txtHint.setText("Click to reveal hint");
		txtAnswer.setText("");
		break;
	}

	curListIndex++;
	
	repaintCustomTextFields();
    }

    private void cmdEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEndActionPerformed
	console.logMsg("Saving current word data...");

	if (isDevMode) {
	    for (Word w : allWords) {
		w.setNumWrong_simplified_hanzi(0);
		w.setNumCorrect_simplified_hanzi(0);
	    }
	}

	csvReader.writeToFile(allWords);
	console.logMsg("Current word data successfully saved. Exiting program...");
	System.exit(0);
    }//GEN-LAST:event_cmdEndActionPerformed

    private void cmdRevealAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRevealAnswerActionPerformed
	if (curWord != null) {
	    switch (curLearningMode) {
		case SIMPLIFIED_HANZI:
		    txtAnswer.setText(curWord.getSimpleHanzi());
		    break;
		case TRADITIONAL_HANZI:
		    txtAnswer.setText(curWord.getSimpleHanzi());
		    break;
		case PINYIN:
		    txtAnswer.setText(curWord.getPinyin());
		    break;
		case TRANSLATE_DE_ZH:
		    txtAnswer.setText(curWord.getSimpleHanzi());
		    break;
		case TRANSLATE_ZH_DE:
		    txtAnswer.setText(curWord.getTranslation());
		    break;
	    }
	} else {
	    JOptionPane.showMessageDialog(this, "Please start a learning session with the menu on the right side first!", "Error", JOptionPane.ERROR_MESSAGE);
	}

	cmdWrong.setEnabled(true);
	cmdCorrect.setEnabled(true);
	
	repaintCustomTextFields();
    }//GEN-LAST:event_cmdRevealAnswerActionPerformed

    private void txtHintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHintMousePressed
	if (curWord != null) {
	    switch (curLearningMode) {
		case SIMPLIFIED_HANZI:
		    txtHint.setText(curWord.getTranslation());
		    break;
		case TRADITIONAL_HANZI:
		    txtHint.setText(curWord.getTranslation());
		    break;
		case PINYIN:
		    txtHint.setText(curWord.getTranslation());
		    break;
		case TRANSLATE_DE_ZH:
		    txtHint.setText(curWord.getPinyin());
		    break;
		case TRANSLATE_ZH_DE:
		    txtHint.setText(curWord.getPinyin());
		    break;
	    }
	} else {
	    JOptionPane.showMessageDialog(this, "Please start a learning session with the menu on the right side first!", "Error", JOptionPane.ERROR_MESSAGE);
	}
	
	repaintCustomTextFields();
    }//GEN-LAST:event_txtHintMousePressed

    private void cmdWrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdWrongActionPerformed
	switch(curLearningMode) {
	    case SIMPLIFIED_HANZI:
		curWord.setNumWrong_simplified_hanzi(curWord.getNumWrong_simplified_hanzi() + 1);
		console.cprintln("   Wrong answer. Stats (wrong/correct): " + curWord.getNumWrong_simplified_hanzi() + " / " + curWord.getNumCorrect_simplified_hanzi());
		break;
	    case TRADITIONAL_HANZI:
		curWord.setNumWrong_traditional_hanzi(curWord.getNumWrong_traditional_hanzi() + 1);
		console.cprintln("   Wrong answer. Stats (wrong/correct): " + curWord.getNumWrong_traditional_hanzi() + " / " + curWord.getNumCorrect_traditional_hanzi());
		break;
	    case PINYIN:
		curWord.setNumWrong_pinyin(curWord.getNumWrong_pinyin() + 1);
		console.cprintln("   Wrong answer. Stats (wrong/correct): " + curWord.getNumWrong_pinyin() + " / " + curWord.getNumCorrect_pinyin());
		break;
	    case TRANSLATE_DE_ZH:
		curWord.setNumWrong_translate_de_zh(curWord.getNumWrong_translate_de_zh() + 1);
		console.cprintln("   Wrong answer. Stats (wrong/correct): " + curWord.getNumWrong_translate_de_zh() + " / " + curWord.getNumCorrect_translate_de_zh());
		break;
	    case TRANSLATE_ZH_DE:
		curWord.setNumWrong_translate_zh_de(curWord.getNumWrong_translate_zh_de() + 1);
		console.cprintln("   Wrong answer. Stats (wrong/correct): " + curWord.getNumWrong_translate_zh_de() + " / " + curWord.getNumCorrect_translate_zh_de());
		break;
	}
	
	curSessionWrong++;
	console.cprintln("Current session (correct/total): " + curSessionCorrect + "/" + (curSessionCorrect + curSessionWrong) + ", percentage: " + 
		String.format("%.2f", (curSessionCorrect / (double) (curSessionCorrect + curSessionWrong)) * 100) + "%");
	
	loadNextWord();
    }//GEN-LAST:event_cmdWrongActionPerformed

    private void cmdCorrectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCorrectActionPerformed
	switch(curLearningMode) {
	    case SIMPLIFIED_HANZI:
		curWord.setNumCorrect_simplified_hanzi(curWord.getNumCorrect_simplified_hanzi() + 1);
		console.cprintln("   Correct answer. Stats (wrong/correct): " + curWord.getNumWrong_simplified_hanzi() + " / " + curWord.getNumCorrect_simplified_hanzi());
		break;
	    case TRADITIONAL_HANZI:
		curWord.setNumCorrect_traditional_hanzi(curWord.getNumCorrect_traditional_hanzi() + 1);
		console.cprintln("   Correct answer. Stats (wrong/correct): " + curWord.getNumWrong_traditional_hanzi() + " / " + curWord.getNumCorrect_traditional_hanzi());
		break;
	    case PINYIN:
		curWord.setNumCorrect_pinyin(curWord.getNumCorrect_pinyin() + 1);
		console.cprintln("   Correct answer. Stats (wrong/correct): " + curWord.getNumWrong_pinyin() + " / " + curWord.getNumCorrect_pinyin());
		break;
	    case TRANSLATE_DE_ZH:
		curWord.setNumCorrect_translate_de_zh(curWord.getNumCorrect_translate_de_zh() + 1);
		console.cprintln("   Correct answer. Stats (wrong/correct): " + curWord.getNumWrong_translate_de_zh() + " / " + curWord.getNumCorrect_translate_de_zh());
		break;
	    case TRANSLATE_ZH_DE:
		curWord.setNumCorrect_translate_zh_de(curWord.getNumCorrect_translate_zh_de() + 1);
		console.cprintln("   Correct answer. Stats (wrong/correct): " + curWord.getNumWrong_translate_zh_de() + " / " + curWord.getNumCorrect_translate_zh_de());
		break;
	}
	
	curSessionCorrect++;
	console.cprintln("Current session (correct/total): " + curSessionCorrect + "/" + (curSessionCorrect + curSessionWrong) + ", percentage: " + 
		String.format("%.2f", (curSessionCorrect / (double) (curSessionCorrect + curSessionWrong)) * 100) + "%");
	
	loadNextWord();
    }//GEN-LAST:event_cmdCorrectActionPerformed

    private void cmdResetWordStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetWordStatsActionPerformed
	for (Word w : allWords) {
	    w.setNumWrong_simplified_hanzi(0);
	    w.setNumCorrect_simplified_hanzi(0);
	}

	console.logMsg("Saving current word data...");
	csvReader.writeToFile(allWords);
	console.logMsg("Current word data successfully saved. Resetting learning mode...");

	applyLearningMode();
    }//GEN-LAST:event_cmdResetWordStatsActionPerformed

    private void repaintCustomTextFields() {
	txtQuestion.revalidate();
	txtQuestion.repaint();
	txtHint.revalidate();
	txtHint.repaint();
	txtAnswer.revalidate();
	txtAnswer.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new frmMain().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboLearningMode;
    private javax.swing.JCheckBox chkL1;
    private javax.swing.JCheckBox chkL10;
    private javax.swing.JCheckBox chkL11;
    private javax.swing.JCheckBox chkL12;
    private javax.swing.JCheckBox chkL2;
    private javax.swing.JCheckBox chkL3;
    private javax.swing.JCheckBox chkL4;
    private javax.swing.JCheckBox chkL5;
    private javax.swing.JCheckBox chkL6;
    private javax.swing.JCheckBox chkL7;
    private javax.swing.JCheckBox chkL8;
    private javax.swing.JCheckBox chkL9;
    private javax.swing.JCheckBox chkTradHanziOnlyIfDifference;
    private javax.swing.JButton cmdCorrect;
    private javax.swing.JButton cmdEnd;
    private javax.swing.JButton cmdLearningModeApply;
    private javax.swing.JButton cmdResetWordStats;
    private javax.swing.JButton cmdRevealAnswer;
    private javax.swing.JButton cmdWrong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner numShuffleBeta;
    private javax.swing.JTextArea txtAnswer;
    private javax.swing.JTextPane txtConsole;
    private javax.swing.JTextArea txtHint;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables

    ConsoleHandler console;
    CSVReader csvReader;
    ArrayList<Word> allWords;
    ArrayList<Word> curList;
    int curListIndex;
    LearningMode curLearningMode;
    boolean[] lessons;
    Word curWord;
    WeightedShuffle weightedShuffle;
    
    int curSessionWrong = 0;
    int curSessionCorrect = 0;
    
    Font smallFont = new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12);
    Font mediumFont = new java.awt.Font("Dialog", java.awt.Font.PLAIN, 24);
    Font largeFont = new java.awt.Font("Dialog", java.awt.Font.PLAIN, 48);

    boolean isDevMode = false;
}
